# Dockerfile to install UKAT libraries
FROM python:3.8

# Install Dependencies
RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y build-essential pkg-config cmake git pigz && \
	apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y

RUN pip install ukat>=0.6.1 validators wget

ADD version.txt .
ADD imgqc.py .
